# Site settings
title:       Tim's world
email:       timqian92@qq.com
author:      Tim Qian
description: "My personal blog"
baseurl:     ""
url:         "http://www.timqian.com"

# Google analytics
google_analytics: UA-56506279-1

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: timqian

# Social icons
show_social_icons: false
github_username: timqian
stackoverflow_id:
twitter_username:
google_plus_id: timqian92@gmail.com
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
